### ISSUE TITLE
MongoDB Sidecar doesn't work with IPv6 enabled

### ISSUE THREAD

**Issue by mkruliv** [morphy2k/k8s-mongo-sidecar#140]
We need to enable IPv6 only for our cluster and got an error when creating a replica set. 
```
      containers:
        - name: mongo
          image: mongo:4
          imagePullPolicy: IfNotPresent
          command:
            - mongod
          args:
            - "--replSet=rs0"
            - "--bind_ip=::"
...
            - "--ipv6"
  ```
 It creates primary on the mongo-0 replica, but other sidecar container crashes
 ```
 > k8s-mongo-sidecar@0.5.0 start /opt/k8s-mongo-sidecar
> node src/index.js

Using mongo port: 27017
Starting up k8s-mongo-sidecar
The cluster domain 'cluster.local' was successfully verified.
Error trying to initialize k8s-mongo-sidecar Error: Failed to get /openapi/v2 and /swagger.json: getaddrinfo ENOTFOUND fd08
    at /opt/k8s-mongo-sidecar/node_modules/kubernetes-client/lib/swagger-client.js:58:15
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.init (/opt/k8s-mongo-sidecar/src/lib/k8s.js:17:12)
    at async Object.init (/opt/k8s-mongo-sidecar/src/lib/worker.js:33:9)
 ```
  Do we have additional parameters for working with IPv6?

**Comment by morphy2k** [comment]
IPv6 is only supported since Kubernetes 1.20 as far as I know. The K8s library used here does not provide support for it.
Actually, I stopped further development for this project because there are better [alternatives](https://github.com/mongodb/mongodb-kubernetes-operator). However, if desired, I am thinking about changing the library that supports newer K8s versions.

**Comment by morphy2k** [comment]
I just took a look at it. Unfortunately, it is more work than just changing the library to support IPv6.

**Comment by mkruliv** [comment]
@morphy2k sorry for bothering you, but maybe you can describe what else except library (as I understand it should be changed from goddy/kubernetes-client to something else, maybe to this one https://github.com/kubernetes-client/javascript) should be done to make it work?
Thanks

**Comment by morphy2k** [comment]
This one would cause problems, and there is probably more.
https://github.com/morphy2k/k8s-mongo-sidecar/blob/30bf80402a03847fdef6716ee1fd205fc6273ba2/src/lib/worker.js#L207-L220
