### ISSUE TITLE
Non force replica set reconfig can only add or remove at most 1 voting member.

### ISSUE THREAD

**Issue by jhughes2112** [morphy2k/k8s-mongo-sidecar#74]
Just got this setup (thank you for your effort!) and my replicas won't join under any circumstances.  When I start with replicas=3, I get the error from the title spewed every 5 seconds.  Here's why, according to Mongo docs:

> **Reconfiguration Can Add or Remove No More than One Voting Member at a Time**
> Starting in MongoDB 4.4, rs.reconfig() by default allows adding or removing no more than 1 voting member at a time. For example, a new configuration can make at most one of the following changes to the cluster membership:
> 
> Adding a new voting replica set member.
> Removing an existing voting replica set member.
> Modifying the votes for an existing replica set member.
> To add or remove multiple voting members, issue a series of rs.reconfig() operations to add or remove one member at a time.
> 
> Issuing a force reconfiguration immediately installs the new configuration even if it adds or removes multiple voting members. Force reconfiguration can cause unexpected behavior, such as the rollback of "majority" committed write operations.

Looks like the replica script has to only make one change per update now.

**Comment by jhughes2112** [comment]
I submitted a PR with fixes for this.

**Comment by morphy2k** [comment]
Fixed with [v0.5.0](https://github.com/morphy2k/k8s-mongo-sidecar/releases/tag/v0.5.0)
Thank you!
